### ISSUE TITLE
Ильназ, прошу разъяснить.

### ISSUE THREAD

**Issue by Alanrus** [Alanrus/05-TaxiService#2]
@coursar 
1) будет ли потеря точности если я таким путем решаю задачу по вычислению процента? (сам я тестировал вручную, все ок, но не хочу верить, хочу проверить).
п.с. 100 - это количество копеек в рубле. 
2) насколько на практике такое решение считается подходящим?
3) какие еще существуют методы вычисления процента от числа целочисленными операторами,  без использования операторов с плавающей точкой?

https://github.com/Alanrus/05-TaxiService/blob/5df55f3ed3c29b7641a65156ac898f215a06fb4c/src/main/java/Order.java#L14-L16

**Comment by coursar** [comment]
1. Дробная часть просто отбросится (это не округление)
2. Нормально
3. Операторов с плавающей точкой не бывает, бывают выражения, в которых участвуют разные типы данных. Тогда действуют правила, которые мы проходили.

**Comment by Alanrus** [comment]
@coursar Ильназ, благодарю за ответы. Как Вы считаете,  какое самое лучшее решение стоит использовать когда нужно точно вычислить процент в выражении исключительно с целочисленными операторами?
   int sumDiscauntAll = (discount * sumOrder() + 100) / 100;

**Comment by coursar** [comment]
Нормальное решение

**Comment by coursar** [comment]
На лекции напомните - обсудим
