### ISSUE TITLE
Имён вроде *1, *2 быть не должно

### ISSUE THREAD

**Issue by coursar** [Alanrus/05-TaxiService#3]
https://github.com/Alanrus/05-TaxiService/blob/5df55f3ed3c29b7641a65156ac898f215a06fb4c/src/main/java/Main.java#L3

**Comment by Alanrus** [comment]
@coursar Ильназ, я переделал, но  вопрос остался, а как тогда лучше называть однотипные объекты? ведь на практике заказов может быть тысячи...

**Comment by coursar** [comment]
Пока никак - потом они просто будут храниться в списке и там уже по ситуации.

Вы же не собираетесь прямо в коде каждому из тысячи объектов присваивать имя?
