### ISSUE TITLE
У else всегда должен быть блок (только если не else if)

### ISSUE THREAD

**Issue by coursar** [Alanrus/05-TaxiService#5]
https://github.com/Alanrus/05-TaxiService/blob/e6ab0b4d9ccc8e584d32480314411c49d09d50e9/src/main/java/Order.java#L16-L21

**Comment by Alanrus** [comment]
@coursar я правильно понял, что нужно все выражения после else заключить в скобки? 
например, else {sumDiscauntAll = 0}; 
Если да, то зачем? (в нашем решении везде используется конструкция if.... else... 
Или я неправильно понял? Ильназ, разъясните, пожалуйста.

**Comment by coursar** [comment]
Потому что, если вы пишите:
```java
if (<expr>) <statement>
else <statement>
```

То рано или поздно вы добавите ещё один:
```java
if (<expr>)
  <statement>
else
  <statement>
  <statement>
```

Но вот последний <statement> уже не будет иметь никакого отношения к else

**Comment by Alanrus** [comment]
Спасибо за это предупреждение. Действительно я об этом не задумывался. Такой подход съэкономил мне часы бесплодных поисков ошибок в коде 👍 
п.с. именно этот код я упростил и обошелся без else.
