### ISSUE TITLE
Сервис одним вызовом должен рассчитывать итоговую сумму

### ISSUE THREAD

**Issue by coursar** [Alanrus/05-TaxiService#6]
https://github.com/Alanrus/05-TaxiService/blob/e6ab0b4d9ccc8e584d32480314411c49d09d50e9/src/main/java/Main.java#L4-L12

Т.е.:

```java
int totalPrice = order.calculatePrice(distance);
```

**Comment by Alanrus** [comment]
@coursar 1. Я правильно понимаю, что в main должно остаться исключительно ссылка на метод (калькулятор) и souts?
т.е., например:
int totalPrice = order.calculatePrice(distance);
System.out.println("Стоимость Вашей поездки: ...)?

2. Если так, то мне важно понять, я всегда должен из main максимально все переносить в параметры объекта? 
3. как по существу понять и различать main и остальные классы?

**Comment by coursar** [comment]
1. Да
2. Да, все входные данные (кроме значений по умолчанию - это пройдём позже) - в параметры метода
3. Main - это просто "запускалка" всего остального
