### ISSUE TITLE
Где блоки для if?

### ISSUE THREAD

**Issue by coursar** [Alanrus/05-TaxiService#7]
https://github.com/Alanrus/05-TaxiService/blob/03263886c82c48d04d40d0e54b4896f88b432e9f/src/main/java/Order.java#L12-L15

**Comment by Alanrus** [comment]
если я не использую else мне все равно следует писать фигурные скобки?

**Comment by coursar** [comment]
да, это убережёт вас от кучи ошибок в будущем
