### ISSUE TITLE
Зачем это поле, если вы в параметр метода передаёте расстояние?

### ISSUE THREAD

**Issue by coursar** [Alanrus/05-TaxiService#8]
https://github.com/Alanrus/05-TaxiService/blob/03263886c82c48d04d40d0e54b4896f88b432e9f/src/main/java/Order.java#L4

**Comment by Alanrus** [comment]
понял) спасибо. 2 раза получается объявил переменную. 
с точки зрения изящности кода лучше наверное объявлять переменную не в параметре метода, а в переменных класса?

**Comment by coursar** [comment]
Зависит от ситуации. В этом случае - лучше параметром метода.
